### ISSUE TITLE
I can't find the model with V-Net elements

### ISSUE THREAD

**Issue by hlyf-xs** [poiuohke/UDC-Net#2]
There are server encoders and decodes modified by V-Net in your paper, but I can't find them.

**Comment by poiuohke** [comment]
Sorry, the model definition is missing in the previous code and I have uploaded the code now. You can find the model definition in 'model.py'.

**Comment by hlyf-xs** [comment]
Appreciate for your quick response! I'll check it out!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "poiuohke/UDC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月8日(星期五) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [poiuohke/UDC-Net] I can't find the model with V-Net elements (#2)





 
Sorry, the model definition is missing in the previous code and I have uploaded the code now. You can find the model definition in 'model.py'.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
